### ISSUE TITLE
Opinion of current code

### ISSUE THREAD

**Issue by Darkman** [lock8/django-rest-framework-jwt-refresh-token#5]
What's your opinion of the current code, is it safe to use or still in development? I really want to use JWTs but really don't get why the django-rest-framework-jwt project wanted this to split into a different project as it seems refresh tokens are a major part of JWTs.

**Comment by ticosax** [comment]
@Darkman, for what it worth, we use it in production. Regarding security, I can't provide any guaranties.
You have to know that `django-rest-framework-jwt` already support refresh tokens. But those refresh tokens are stateless like `JWT`s are.
The kind of refresh token this project is providing are a different kind. They are stateful, and such property didn't make it a good fit for the mainstream project. Because not everyone is interested in having persisted refresh tokens.

**Comment by Darkman** [comment]
@ticosax, Yeah, I am wanting to follow the auth0 approach where there are short lived access tokens (5-15 min) and also longer lived refresh tokens (days-whenever). Also the refresh tokens should be able to revoked and such, which is where these two projects come in, drf-jwt for the access tokens (stateless) and this one for the refresh tokens (stateful (revokable)). I see in the docs that the refresh tokens do not expire, how hard would it be to add an expiration setting to them?

**Comment by Darkman** [comment]
Also, just as a semantics argument, I wouldn't say the django-rest-framework-jwt projects supports refresh tokens, more so that it supports "refreshing" tokens and not a different independent 'refresh' token.
